services:
  rate-limiter:
    build: .
    container_name: rate-limiter-service
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ConnectionStrings__Redis: redis:6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis-db
    ports:
      - "6379:6379"